name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FLUTTER_VERSION: "3.22.1"  # Актуальная стабильная версия
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Validate project
        run: |
          [ -f "pubspec.yaml" ] || { echo "❌ Отсутствует pubspec.yaml"; exit 1; }
          [ -d "android" ] || { echo "❌ Отсутствует папка android/"; exit 1; }

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: voice-assistant-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 3
