name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      FLUTTER_VERSION: "3.22.1"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable

      - name: Validate Android structure
        run: |
          [ -f "android/app/build.gradle" ] || { echo "❌ Отсутствует android/app/build.gradle"; exit 1; }
          grep "multiDexEnabled true" android/app/build.gradle || { echo "❌ Не настроен MultiDex"; exit 1; }

      - name: Install dependencies
        run: |
          flutter pub upgrade --major-versions
          flutter pub get

      - name: Build APK (with null safety)
        run: flutter build apk --release --no-sound-null-safety

      - uses: actions/upload-artifact@v4
        with:
          name: voice-assistant-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 3
